baseurl = "https://kahlillechelt.com"
languageCode = "en-us"
title = "kahlillechelt.com"
googleAnalytics = ""
disqusShortname = ""
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
enableEmoji = true

[permalinks]
  post = "/:year/:month/:day/:slug"

[[menu.main]]
  name = "Podcast"
  url = "/podcast/"
  weight = 1
[[menu.main]]
  name = "Twitter"
  url = "https://twitter.com/kahliltweets"
  weight = 2
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3
[[menu.main]]
  name = "Feed"
  url = "/index.xml"
  weight = 4

[params]
  description = "A blog by Kahlil Lechelt"
  footer = "&copy; [Kahlil Lechelt](https://kahlil.info) 2017 | [Github](https://github.com/kahlil) | [Twitter](https://twitter.com/kahliltweets)"

[outputs]
  home = ["html", "json", "rss"]
  section = ["html", "json", "rss"]

[taxonomies]
  tag = "tags"