[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
YARN_VERION = "1.22.4"
NODE_VERION = "12.16.3"
HUGO_VERSION = "0.71"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo  --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.71"

[context.branch-deploy]
command = "hugo  --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.71"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
