name = "Ka"
license = "MIT"
description = "Person theme of Kahlil Lechelt"
homepage = "https://www.kahlillechelt.com"
features = ["blog"]
min_version = "0.20"

[author]
  name = "Kahlil Lechelt"
  homepage = "https://www.kahlillechelt.com"
